# Generated by Django 4.2.3 on 2023-09-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_alter_voiture_typee'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre_dor',
            name='verifier',
            field=models.BooleanField(default=False),
        ),
    ]
